[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zshmarks"]
    type = "git-repo"
    url = "https://github.com/jocelynmallon/zshmarks.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-kitty"]
    type = "git-repo"
    url = "https://github.com/redxtech/zsh-kitty.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}
["bin/nvim.appimage"]
    type = "file"
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    executable = true
    refreshPeriod = "168h"
{{ else if eq .chezmoi.os "darwin" -}}
["bin/nvim-macos"]
    type = "archive"
    exact = true
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-macos.tar.gz"
    refreshPeriod = "168h"
{{ end -}}
