[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zshmarks"]
    type = "git-repo"
    url = "https://github.com/jocelynmallon/zshmarks.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-kitty"]
    type = "git-repo"
    url = "https://github.com/redxtech/zsh-kitty.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}

["bin/nvim-linux.appimage"]
    type = "file"
    {{ if eq .chezmoi.arch "arm" }}
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-arm64.appimage"
    {{ else }}
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
    {{ end -}}
    executable = true
    refreshPeriod = "168h"

{{ else if eq .chezmoi.os "darwin" -}}
["bin/nvim-macos"]
    type = "archive"
    exact = true
    {{ if eq .chezmoi.arch "arm64" }}
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-macos-arm64.tar.gz"
    {{ else }}
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-macos-x86_64.tar.gz"
    {{ end -}}
    stripComponents = 1
    refreshPeriod = "168h"
{{ end -}}

{{ if eq .chezmoi.os "linux" -}}
["bin/code-minimap"]
    type = "archive-file"
    {{ if eq .chezmoi.arch "arm" }}
    url = "https://github.com/wfxr/code-minimap/releases/download/v0.6.8/code-minimap-v0.6.8-aarch64-unknown-linux-musl.tar.gz"
    {{ else }}
    url = "https://github.com/wfxr/code-minimap/releases/download/v0.6.8/code-minimap-v0.6.8-x86_64-unknown-linux-musl.tar.gz"
    {{ end -}}
    path = "code-minimap"
    stripComponents = 1
    executable = false
    refreshPeriod = "168h"
{{ end -}}

["bin/delta"]
    type = "archive-file"
{{ if eq .chezmoi.os "linux" -}}
    {{ if eq .chezmoi.arch "arm" }}
    url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-unknown-linux-gnu.tar.gz"
    {{ else }}
    url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-musl.tar.gz"
    {{ end -}}
{{ else if eq .chezmoi.os "darwin" -}}
    {{ if eq .chezmoi.arch "arm" }}
    url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-apple-darwin.tar.gz"
    {{ else }}
    url = "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-apple-darwin.tar.gz"
    {{ end -}}
{{ end -}}
    path = "delta"
    stripComponents = 1
    executable = true
    refreshPeriod = "168h"

["bin/rg"]
    type = "archive-file"
{{ if eq .chezmoi.os "linux" -}}
    {{ if eq .chezmoi.arch "arm" }}
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-armv7-unknown-linux-musleabi.tar.gz"
    {{ else }}
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz"
    {{ end -}}
{{ else if eq .chezmoi.os "darwin" -}}
    {{ if eq .chezmoi.arch "arm" }}
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-aarch64-apple-darwin.tar.gz"
    {{ else }}
    url = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-apple-darwin.tar.gz"
    {{ end -}}
{{ end -}}
    path = "rg"
    stripComponents = 1
    executable = true
    refreshPeriod = "168h"
