[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zshmarks"]
    type = "git-repo"
    url = "https://github.com/jocelynmallon/zshmarks.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-kitty"]
    type = "git-repo"
    url = "https://github.com/redxtech/zsh-kitty.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}
["bin/nvim-linux64"]
    type = "archive"
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
{{ else if eq .chezmoi.os "darwin" -}}
["bin/nvim-macos"]
    type = "archive"
    exact = true
    {{ if eq .chezmoi.arch "arm64" }}
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-macos-arm64.tar.gz"
    {{ else }}
    url = "https://github.com/neovim/neovim/releases/latest/download/nvim-macos-x86_66.tar.gz"
    {{ end -}}
    stripComponents = 1
    refreshPeriod = "168h"
{{ end -}}
