#!/bin/bash

#Configures current active virtual env to handle Ruby and Node environments

if [ ! $VIRTUAL_ENV ]; then
    echo -e "\e[31mNot in a Virtual Environment. Aborting.\e[m"
    exit
fi

if [ $VIRTUALENVWRAPPER_HOOK_DIR ]; then
    venv_hook_dir=$VIRTUALENVWRAPPER_HOOK_DIR
else
    venv_hook_dir=$HOME/.virtualenv
fi

post_activate_lines=(
    'export GEM_HOME="$VIRTUAL_ENV/gems"'
    'export GEM_PATH=""'
    'export GOROOT="$VIRTUAL_ENV"'
    'export PATH=$PATH:"$GEM_HOME/bin"'
    'autoenv_init'
)
for line in "${post_activate_lines[@]}"
do
    if [[ ! `grep "$line" $venv_hook_dir/postactivate` ]];then
        echo -e "\e[32mAdding line to postactivate: $line\e[m"
        echo "$line" >> $venv_hook_dir/postactivate
    fi
done

if [[ ! `which nodeenv` ]]; then
    echo -e "\e[32mInstalling nodeenv\e[m"
    pip install nodeenv
fi
if [ ! `which node` ] || [ `which node` == "$VIRTUAL_ENV*" ]; then
    echo -e "\e[32mInstalling node-js\e[m"
    nodeenv -p install
fi
