#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd -P`
popd > /dev/null

ln -snf $SCRIPT_PATH/aliases $HOME/.aliases
ln -snf $SCRIPT_PATH/bash_aliases $HOME/.bash_aliases
ln -snf $SCRIPT_PATH/bashrc $HOME/.bashrc
ln -snf $SCRIPT_PATH/screenrc $HOME/.screenrc
