#!/bin/bash

excluded_files='setupdotfiles setupmac README bootstrap_venv install_linters bin zsh_plugins config'

pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd -P`
popd > /dev/null

for file in $SCRIPT_PATH/*
do
    filename=`basename $file`
    if [[ ! $excluded_files =~ $filename ]]; then
        echo "linking .$filename"
        ln -snf $file $HOME/.$filename
    fi
done

if [ ! -d "$HOME/bin" ]; then
    mkdir $HOME/bin
fi
for file in $SCRIPT_PATH/bin/*
do
    filename=`basename $file`
    if [[ ! $excluded_files =~ $filename ]]; then
        echo "linking bin/$filename"
        ln -snf $file $HOME/bin/$filename
    fi
done


if [ ! -d "$HOME/.config" ]; then
    mkdir $HOME/.config
fi
for file in $SCRIPT_PATH/config/*
do
    filename=`basename $file`
    if [[ ! $excluded_files =~ $filename ]]; then
        echo "linking config/$filename"
        ln -snf $file $HOME/.config/$filename
    fi
done

for file in $SCRIPT_PATH/zsh_plugins/*
do
    filename=`basename $file`
    if [[ ! $excluded_files =~ $filename ]]; then
        echo "linking zsh_plugins/$filename"
        ln -snf $file $HOME/.oh-my-zsh/custom/plugins/$filename
    fi
done

echo "cloning submodules"
(cd $SCRIPT_PATH && git submodule update --init --recursive)

echo "installing powerline"
if [ "`which pip3`" ]; then
    pip3 install powerline-status
fi
