#!/bin/bash

excluded_files='setupdotfiles README'

pushd `dirname $0` > /dev/null
SCRIPT_PATH=`pwd -P`
popd > /dev/null

for file in $SCRIPT_PATH/*
do
    filename=`basename $file`
    if [[ ! $excluded_files =~ $filename ]]; then
        echo "linking .$filename"
        ln -sf $file $HOME/.$filename
    fi
done

(cd $SCRIPT_PATH && git submodule update --init --recursive)
vim +BundleInstall +qa
