#!/bin/bash

excluded_files='setupdotfiles README'

for file in *
do
    if [[ ! $excluded_files =~ $file ]]; then
        ln -sf $PWD/$file $HOME/.$file
    fi
done

git submodule update --init --recursive
vim +BundleInstall +qa
