name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Vint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install
        run: |
          pip install vim-vint
          pip install pre-commit
      - name: Run Vint
        run: |
          pre-commit run --all-files || { git diff --color=always && exit 1; }
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1.2.6
        with:
          neovim: true
      - name: Ensure plugins directory exists
        run: |
          mkdir -p $HOME/.config/nvim/plugins
      - name: Create a fake code-minimap executable
        # Necessary for minimap.vim to start up
        run: |
          mkdir -p "$HOME/bin"
          ln -s /bin/echo "$HOME/bin/code-minimap"
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Checkout Testify
        run: |
          git clone --depth 1 https://github.com/dhruvasagar/vim-testify $HOME/.config/nvim/plugins/vim-testify
      - name: Run Unit Tests
        run: |
          nvim -c "set rtp+=$HOME/.config/nvim/plugins/vim-testify" -c "set rtp+=./" -S $HOME/.config/nvim/plugins/vim-testify/plugin/testify.vim -S ./plugin/minimap.vim +TestifySuite
